### ISSUE TITLE
The Docker image is not built.

### ISSUE THREAD

**Issue by kartblanch** [typpo/quickchart#149] opened 2022-12-29 10:47 UTC
After executing the command `docker build -t ianw/quickchart .` I have this error: 

> ERROR: unable to select packages:
>   so:libtiff.so.6 (no such package):
>     required by: vips-8.13.3-r2[so:libtiff.so.6]

I use 1.8 version for built this docker image. Any ideas how to fix this error?

**Comment by markblinkhorn** [comment] 2022-12-29 18:10
You can sidestep the issue by commenting out the 'RUN apk add vips-dev' line in Dockerfile. This will force it to build without vips-dev. I have no idea what it will break - but mine seems to work ;-)

**Comment by typpo** [comment] 2022-12-29 19:39
Acknowledged - I plan to troubleshoot this soon.  My hunch is that landing https://github.com/typpo/quickchart/pull/144 will also address this problem.

**Comment by Jacek-ghub** [comment] 2022-12-31 04:24
I also got this error.  

Maybe a short comment in the Dockerfile would help others resolve it faster?  (For time being, until the issue is not addressed.)

**Comment by kartblanch** [comment] 2023-01-11 07:08
> I also got this error.
> 
> Maybe a short comment in the Dockerfile would help others resolve it faster? (For time being, until the issue is not addressed.)

I support! A good idea!

**Comment by typpo** [comment] 2023-05-14 03:17
The Dockerfile has been updated and this error should be resolved by https://github.com/typpo/quickchart/commit/2297078bb1abfde338064f154c5d1801f2bf03d2

**Closed by typpo** 2023-05-14 03:17 UTC
