### ISSUE TITLE
Line graph dashed line not working

### ISSUE THREAD

**Issue by CharlieTap** [typpo/quickchart#19] opened 2019-08-08 16:32 UTC
Attempting to make a line graph with a simple dashed line and its not quite working, oddly it works just fine when using chart.js directly.

```json
{
   "type":"line",
   "data":{
      "labels":[
         "July 19",
         "August 19",
         "Sept 19"
      ],
      "datasets":[
         {
            "data":[
               1.2,
               1.4
            ],
            "label":"Progress",
            "borderColor":"#1c60ab",
            "borderDash":[
               5,
               5
            ],
            "pointBackgroundColor":"#1c60ab"
         },
         {
            "data":[
               1.2,
               1.5,
               1.8
            ],
            "label":"Target",
            "borderColor":"#d7d8da",
            "borderDash":[
               5,
               5
            ],
            "pointBackgroundColor":"#d7d8da",
            "pointRadius":0
         }
      ]
   },
   "options":{
      "plugins":{
         "datalabels":{
            "display":false
         }
      },
      "scales":{
         "yAxes":[
            {
               "ticks":{
                  "beginAtZero":false
               }
            }
         ]
      },
      "elements":{
         "line":{
            "fill":false
         }
      }
   }
}
```

**Comment by typpo** [comment] 2019-08-08 22:17
Hi @CharlieTap,

This one took me a while to figure out.  It's caused by this bug in the `vm2` package, which is how we run sandboxed code for each chart: https://github.com/patriksimek/vm2/issues/198

I put in a workaround that fixes the malformed array object that is produced, so things look good now:

![image](https://user-images.githubusercontent.com/310310/62741271-2e806700-b9ef-11e9-9c62-9617e5ce9c07.png)

Your browser may have cached the bad (non-dashed) images.  If images you've loaded in the past are still rendering incorrectly you can clear your cache, change you config object slightly, or add a cache-busting param (e.g. `q=<timestamp>`) to your request in order to see the corrected graphs.

I'll keep this issue open until `vm2` has fixed the problem and I can remove the workaround.

**Comment by CharlieTap** [comment] 2019-08-09 07:52
Perfect thank you

**Comment by typpo** [comment] 2020-01-31 21:52
Closing this now as the workaround is documented in code.  Thanks for the report :)

**Closed by typpo** 2020-01-31 21:52 UTC
